using System;

namespace BoCode.RedoDB.RedoableData
{
    /// <summary>
    /// Your redoable system should use this class to get new
    /// Guids in a redoable way (recoverable Guids are needed when the system recovers from commandlog).
    /// Don't use Guid.NewGuid() in your system as Guid.NewGuid is non predeterministic. RedoableGuid generates a Guid and save it for recovering or returns 
    /// the Guid generated by the command on first execution while recovering. 
    /// If your system implments the Interface IDependsOnRedoableGuid, a dedicated instance of RedoableGuid is injected in your system at the time you build 
    /// the RedoDBEngine for your system.
    /// </summary>
    public class RedoableGuid : RedoableData<Guid>, IRedoableGuid
    {
        private static RedoableGuid? _singleton = null;

        public RedoableGuid() : base(() => Guid.NewGuid()) { }
    }
}
